# 1,修改成你的分支
on:
  push:
    branches: [ boot270-docker ]
  pull_request:
    branches: [ boot270-docker ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml



    # 2 Docker镜像打包 （--tag后可以修改成你的镜像名称）
    - name: BuildDockerImage
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    # 2.1发布到DockerHub  (修改成uses后面修改成你的仓库路径@分支)
    - name: Publish to Docker Repository
      uses: ghjohn/boot270@boot270-docker
    # name改成你DockerHub仓库地址：username和password这里改成你GitHub中配置的敏感环境变量
      with:
        name: keygenee/priv-demo:iamtagname
        username: ${{ docker-secrets.DOCKER_HUB_PASSWORD }}
        password: ${{ docker-secrets.DOCKER_HUB_USERNAME }}
